apiVersion: batch/v1
kind: Job
metadata:
  name: example-indexed-job
spec:
  parallelism: 2
  completions: 2
  completionMode: Indexed
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: training-job-sa
      restartPolicy: Never
      containers:
      - name: main
        image: local/jax:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 900m
            nvidia.com/gpu: 1
        command: 
          - python
        args:
          - -c
          - |
            import jax
            import time
            time.sleep(100000)
            jax.distributed.initialize()
            print(jax.devices())
            print(jax.local_devices())
            assert jax.process_count() > 1
            assert len(jax.devices()) > len(jax.local_devices())
