apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: example
spec:
  network:
    publishNotReadyAddresses: false
  replicatedJobs:
  - name: workers
    template:
      spec:
        parallelism: 2
        completions: 2
        backoffLimit: 0
        template:
          spec:
            serviceAccountName: training-job-sa
            restartPolicy: Never
            imagePullSecrets: 
            - name: null
            containers:
            - name: main
              image: local/jax:latest
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: 900m
                  nvidia.com/gpu: 1
              command:
                - bash
                - -c
                - |
                  python <<EOF
                  import jax
                  jax.distributed.initialize()
                  print(jax.devices())
                  print(jax.local_devices())
                  assert jax.process_count() > 1
                  assert len(jax.devices()) > len(jax.local_devices())
                  EOF
              readinessProbe:
                exec:
                  command:
                    - bash
                    - -c
                    - |
                      if [[ $JOB_COMPLETION_INDEX == 0 ]]; then
                        sleep 1
                      fi
                      exit 0
                initialDelaySeconds: 0
                periodSeconds: 1
                timeoutSeconds: 10
                failureThreshold: 10
